In [41]:
import numpy as np

In [42]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [43]:
np.__version__

'2.2.6'

In [44]:
my_list  = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [45]:
type(my_list)

list

In [46]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [47]:
type(arr)

numpy.ndarray

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [52]:
np.arange(20,8)

array([], dtype=int64)

In [53]:
np.arange(-20,8) #first number should be < second number

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [54]:
n = np.arange(-20,8)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [55]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.zeros(3,dtype = int)

array([0, 0, 0])

In [57]:
np.zeros(3,dtype = str)

array(['', '', ''], dtype='<U1')

In [58]:
np.zeros(3,dtype = bool)

array([False, False, False])

In [59]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [62]:
np.zeros(0)

array([], dtype=float64)

In [63]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [64]:
nd = np.zeros((5,9) , dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
np.ones(3)

array([1., 1., 1.])

In [66]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [67]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [69]:
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [70]:
rand(3,2)

NameError: name 'rand' is not defined

In [71]:
np.rand(23,3)

AttributeError: module 'numpy' has no attribute 'rand'

In [72]:
import random as rand


TypeError: 'module' object is not callable. Did you mean: 'random.random(...)'?

In [73]:
np.random.rand(2)

array([0.16205504, 0.82872585])

In [74]:
np.random.rand(2)

array([0.04061917, 0.92454253])

In [75]:
np.random.rand(3)

array([0.72124161, 0.14015622, 0.04578068])

In [76]:
np.random.rand(3)

array([0.08296207, 0.04853086, 0.12021124])

In [81]:
np.random.rand(2, 2)

array([[0.29901726, 0.19759093],
       [0.22806791, 0.1145472 ]])

In [105]:
np.random.randint(9)

3

In [127]:
np.random.randint(2,10) # 2 included uptil 9

7

In [133]:
np.random.randint(2,10,3)

array([6, 4, 6], dtype=int32)

In [153]:
print(np.random.randint(2,10,4))

[4 9 4 3]


In [156]:
print(np.random.randint(2,10,4)[0])

5


In [162]:
print(np.random.randint(-30,20,10))

[-29 -18  -6   6  -6   0 -17  19 -23   9]


In [193]:
np.random.randint(10,40,(10,10))

array([[18, 23, 35, 23, 13, 28, 29, 28, 32, 14],
       [23, 31, 27, 17, 32, 35, 16, 18, 19, 37],
       [24, 16, 21, 18, 16, 33, 10, 14, 18, 16],
       [20, 11, 39, 39, 37, 25, 27, 29, 13, 32],
       [15, 28, 17, 36, 21, 25, 38, 31, 10, 19],
       [13, 12, 18, 14, 17, 18, 37, 10, 12, 20],
       [22, 22, 28, 19, 26, 13, 21, 22, 18, 18],
       [27, 15, 38, 17, 13, 21, 34, 34, 33, 20],
       [35, 32, 36, 11, 32, 18, 16, 17, 37, 16],
       [13, 33, 38, 28, 20, 29, 21, 32, 27, 30]], dtype=int32)

In [194]:
m = np.random.randint(10,40,(10,10))
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [195]:
arr

array([0, 1, 2, 3, 4, 5])

In [196]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [198]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [199]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [201]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [203]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

# Slicing in Matrix

In [204]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [207]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [208]:
type(b)

numpy.ndarray

In [209]:
b[:]

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [210]:
b[1:4]

array([[19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10]], dtype=int32)

In [211]:
b[0:0]

array([], shape=(0, 4), dtype=int32)

In [212]:
b[1:1]

array([], shape=(0, 4), dtype=int32)

In [213]:
b[-1:1]

array([], shape=(0, 4), dtype=int32)

In [214]:
b[-4:-2]

array([[19, 16, 16, 14],
       [13, 16, 17, 19]], dtype=int32)

In [215]:
b

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [216]:
b[-1:]

array([[13, 10, 13, 16]], dtype=int32)

In [217]:
b[:-1]

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10]], dtype=int32)

In [218]:
b

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [219]:
b[:-1]

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10]], dtype=int32)

In [220]:
b[:-2]

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19]], dtype=int32)

In [221]:
b

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [222]:
b[1:3]

array([[19, 16, 16, 14],
       [13, 16, 17, 19]], dtype=int32)

In [224]:
print(b[1,3])

14


In [226]:
print(b[4,3])

16


In [227]:
b

array([[16, 11, 15, 12],
       [19, 16, 16, 14],
       [13, 16, 17, 19],
       [18, 18, 19, 10],
       [13, 10, 13, 16]], dtype=int32)

In [228]:
print(b[1,-1])

14


In [229]:
print(b[2,-1])

19


# Numpy Operations

In [230]:
arr

array([0, 1, 2, 3, 4, 5])

In [231]:
arr.max()

np.int64(5)

In [232]:
arr.min()

np.int64(0)

In [233]:
from numpy import *
arr
median(arr)

np.float64(2.5)

# Indexing in Numpy

In [234]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [235]:
row = 4
col = 5

In [236]:
m[row,col]

np.int32(23)

In [241]:
m[1,:]  # To print row from the matrix

array([39, 22, 15, 12, 24, 31, 34, 35, 30, 32], dtype=int32)

In [242]:
m[:,col] # To print column from the matrix


array([38, 31, 18, 21, 23, 11, 36, 39, 27, 23], dtype=int32)

In [243]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [244]:
m[::-1] # reverse the matrix

array([[17, 29, 31, 33, 29, 23, 24, 21, 22, 17],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [25, 38, 38, 18, 30, 38, 34, 16, 29, 11]], dtype=int32)

In [245]:
m[::-2]

array([[17, 29, 31, 33, 29, 23, 24, 21, 22, 17],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32]], dtype=int32)

In [246]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [247]:
m[2:6 , 2:4]

array([[34, 37],
       [19, 17],
       [27, 31],
       [27, 25]], dtype=int32)

In [248]:
m[2:6]

array([[27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28]], dtype=int32)

In [249]:
m[2:4]

array([[27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16]], dtype=int32)

In [251]:
m[:, 2:4]

array([[38, 18],
       [15, 12],
       [34, 37],
       [19, 17],
       [27, 31],
       [27, 25],
       [27, 20],
       [31, 14],
       [27, 34],
       [31, 33]], dtype=int32)

In [252]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [253]:
m[1:2 , 2:4]

array([[15, 12]], dtype=int32)

In [254]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [255]:
m[3:5,2:4]

array([[19, 17],
       [27, 31]], dtype=int32)

# Masking / Filter

In [256]:
m

array([[25, 38, 38, 18, 30, 38, 34, 16, 29, 11],
       [39, 22, 15, 12, 24, 31, 34, 35, 30, 32],
       [27, 25, 34, 37, 29, 18, 31, 35, 12, 33],
       [19, 21, 19, 17, 12, 21, 33, 31, 34, 16],
       [26, 38, 27, 31, 18, 23, 15, 18, 24, 11],
       [21, 37, 27, 25, 17, 11, 28, 35, 35, 28],
       [28, 31, 27, 20, 10, 36, 31, 13, 39, 21],
       [14, 25, 31, 14, 32, 39, 37, 14, 10, 30],
       [38, 27, 27, 34, 16, 27, 19, 30, 25, 27],
       [17, 29, 31, 33, 29, 23, 24, 21, 22, 17]], dtype=int32)

In [257]:
m>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [258]:
mat = np.arange(1,101).reshape(10,10)
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [259]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [261]:
mat[mat>50]

array([ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [262]:
mat[mat>=50]

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [263]:
mat[mat==50]

array([50])

In [264]:
mat[mat<50]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [265]:
mat[mat<=50]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [266]:
mat[mat!=50]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])